package com.gestdepo.dao.impl.dummy;

import java.util.ArrayList;
import java.util.List;

import com.gestdepo.model.ExerciseVO;
import com.gestdepo.model.MaterialVO;

public class ExerciseList {
		
	static public List<ExerciseVO> exercises = new ArrayList<ExerciseVO>();
	static {
		MaterialVO m = new MaterialVO(1L, "Ball", 1);
		List<MaterialVO> materials = new ArrayList<MaterialVO>();
		materials.add(m);
		ExerciseVO e = new ExerciseVO(1L, "Rondo 5X2", "Description para el rondo", 7, "Objetive of the exercise", materials, 0l,
				"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA8UAAADICAYAAADBREMvAAAUxElEQVR4Xu3dWYsVVxcG4GqHtPOUOOIAalBvvB"
				+ "ByE0H9F/4tf443Xokg6JVeaEiIomja2cTEGFvtj1VQTeXQLdFvOayznwNF1Rl6ufezdiBvV53qmYWFhYXOgwABAgQIECBAgAABAgQINCgw"
				+ "IxQ32HVTJkCAAAECBAgQIECAAIFeQCi2EAgQIECAAAECBAgQIECgWQGhuNnWmzgBAgQIECBAgAABAgQICMXWAAECBAgQIECAAAECBAg0Ky"
				+ "AUN9t6EydAgAABAgQIECBAgAABodgaIECAAAECBAgQIECAAIFmBYTiZltv4gQIECBAgAABAgQIECAgFFsDBAgQIECAAAECBAgQINCsgFDc"
				+ "bOtNnAABAgQIECBAgAABAgSEYmuAAAECBAgQIECAAAECBJoVEIqbbb2JEyBAgAABAgQIECBAgIBQbA0QIECAAAECBAgQIECAQLMCQnGzrT"
				+ "dxAgQIECBAgAABAgQIEBCKrQECBAgQIECAAAECBAgQaFZAKG629SZOgAABAgQIECBAgAABAkKxNUCAAAECBAgQIECAAAECzQoIxc223sQJ"
				+ "ECBAgAABAgQIECBAQCi2BggQIECAAAECBAgQIECgWQGhuNnWmzgBAgQIECBAgAABAgQICMXWAAECBAgQIECAAAECBAg0KyAUN9t6EydAgA"
				+ "ABAgQIECBAgAABodgaIECAAAECBAgQIECAAIFmBYTiZltv4gQIECBAgAABAgQIECAgFFsDBAgQIECAAAECBAgQINCsgFDcbOtNnAABAgQI"
				+ "ECBAgAABAgSEYmuAAAECBAgQIECAAAECBJoVEIqbbb2JEyBAgAABAgQIECBAgIBQbA0QIECAAAECBAgQIECAQLMCQnGzrTdxAgQIECBAgA"
				+ "ABAgQIEBCKrQECBAgQIECAAAECBAgQaFZAKG629SZOgAABAgQIECBAgAABAkKxNUCAAAECBAgQIECAAAECzQoIxc223sQJECBAgAABAgQI"
				+ "ECBAQCi2BggQIECAAAECBAgQIECgWQGhuNnWmzgBAgQIECBAgAABAgQICMXWAAECBAgQIECAAAECBAg0KyAUN9t6EydAgAABAgQIECBAgA"
				+ "ABodgaIECAAAECBAgQIECAAIFmBYTiZltv4gQIECBAgAABAgQIECAgFFsDBAgQIECAAAECBAgQINCsgFDcbOtNnAABAgQIECBAgAABAgSE"
				+ "YmuAAAECBAgQIECAAAECBJoVEIqbbb2JEyBAgAABAgQIECBAgIBQbA0QIECAAAECBAgQIECAQLMCQnGzrTdxAgQIECBAgAABAgQIEBCKrQ"
				+ "ECBAgQIECAAAECBAgQaFZAKG629SZOgAABAgQIECBAgAABAkKxNUCAAAECBAgQIECAAAECzQoIxc223sQJECBAgAABAgQIECBAQCi2BggQ"
				+ "IECAAAECBAgQIECgWQGhuNnWmzgBAgQIECBAgAABAgQICMXWAAECBAgQIECAAAECBAg0KyAUN9t6EydAgAABAgQIECBAgAABodgaIECAAA"
				+ "ECBAgQIECAAIFmBYTiZltv4gQIECBAgAABAgQIECAgFFsDBAgQIECAAAECBAgQINCsgFDcbOtNnAABAgQIECBAgAABAgSEYmuAAAECBAgQ"
				+ "IECAAAECBJoVEIqbbb2JEyBAgAABAgQIECBAgIBQbA0QIECAAAECBAgQIECAQLMCQnGzrTdxAgQIECBAgAABAgQIEBCKrQECBAgQIECAAA"
				+ "ECBAgQaFZAKG629SZOgAABAgQIECBAgAABAkKxNUCAAAECBAgQIECAAAECzQoIxc223sQJECBAgAABAgQIECBAQCi2BggQIECAAAECBAgQ"
				+ "IECgWQGhuNnWmzgBAgQIECBAgAABAgQICMXWAAECBAgQIECAAAECBAg0KyAUN9t6EydAgAABAgQIECBAgAABodgaIECAAAECBAgQIECAAI"
				+ "FmBYTiZltv4gQIECBAgAABAgQIECAgFFsDBAgQIECAAAECBAgQINCsgFDcbOtNnAABAgQIECBAgAABAgSEYmuAAAECBAgQIECAAAECBJoV"
				+ "EIqbbb2JEyBAgAABAgQIECBAgIBQbA0QIECAAAECBAgQIECAQLMCQnGzrTdxAgQIEJgGgT/++KN7+PBh9+jRo8Xt6tWr3fz8fHfkyJFuw4"
				+ "YN3e7du7uzZ8++2bp1azc3N7dqGuZtDgQIECBAIEtAKM6SVIcAAQIECHygwOvXr7sItS9evOiePXvW/f777/0Wrz948KC7efNm/96aNWv6"
				+ "958/f/6vLd6bnZ3tduzY0W3fvn1xi2HEz6xbt677888/u7Vr13b79+9/+cMPP3Q//vjjug8cpo8TIECAAIGpFhCKp7q9JkeAAAECn0rgr7"
				+ "/+6gPtEGSH42G/YsWK7vbt24vvD587cOBAd/Hixf5n3717123atKk7depU/9nNmzf329GjR7uoH4F2y5Yt3bFjx7o4yxvH423btm1d/Dse"
				+ "BAgQIECAwMcLCMUfb+cnCRAgQKCoQITNOOsaQXXYD6F1vI/p3blzp//cZACOM7GnT5/ufv311z7IRrgd7/fv39/rDEF32EeQjUua4/NRw4"
				+ "MAAQIECBD4sgJC8Zf1968TIECAwEcIvHnzpnvy5En3+PHjxS2eX7t2rQ+w69evX/Is7hB4I7DGWdoIqnHmdTK4Ds+/++67/hLkcdgdjleu"
				+ "XPkRI/cjBAgQIECAwNcmIBR/bR2ZovHMzMy86bpuxfnz51fE99ji7IgHAQIEJgWWC7hD4B2H3+E4Li3+9ttvuwitwxbP47u4cZlx3GBqOH"
				+ "M7GWjjuQcBAgQIECBAYBAQiq2FTyZw7ty5+xcuXFg7Pz+/9cqVK92ZM2e6v//+uzt8+HC/ff/9992hQ4e6ffv29TeB8SBAoLZAXF4cN4N6"
				+ "+vRpv3/f8fBe3CF5bm5uyYA7DruTx4Jt7bVi9AQIECBA4GsSEIq/pm5M+Vhu3brV30n1l19+6beff/65/5/nuNwxLnWMcByXNK5evbo/Pn"
				+ "78eLdz587+rqqxjy3e8yBA4NMITN4oavJ7tHFDp/j+7HJhN74nG2dp46qQ2L/veHgvPivgfpp+qkqAAAECBAj8NwGh+L85+dQnFojLJO/e"
				+ "vdvf0Oby5cvdb7/91s3MzPR/kiT+/mbsY4v/6R6H5CEsD6/F2aTxnVkjbHsQmGaBly9f9ncontzi8uK4LDn+uxnfIGoy6I6fT94oavKy4/"
				+ "ilVQTj5cKuuyBP80ozNwIECBAgML0CQvH09nYqZxZnqMYheQjLw2sRrsd/x/Off/5ZDMmTf85k+E7iiRMnut27d3d79+7tv4MYoXrjxo1T"
				+ "6WdSX14g/q5shNRhm3z+008/dRF0Yw0uFXYnX4uvHsQviya3+IVQfD3h1atX//pu7VLfrx3C8JfXMQICBAgQIECAwOcXEIo/v7l/8TMKxJ"
				+ "myISRHoB4H5ggfcfn2wsJCf2Y6QvOlS5f6z0QoiecnT57sz15HwIjQEfvhOC7xju9Ix59UiWAyuUWoiTNn33zzTb/Nzs4uHo+fx+txF9s4"
				+ "M+7x5QRiHUSAjC1+mTIcTz4fvzccR//u37/fB933hd54L9ZFhNBhm3w+fCa+d79U2J18zbr5cmvGv0yAAAECBAhMh4BQPB19NItkgbdv3/"
				+ "bfmxwuLY2zynGGLvbDcQTeOEMdoSnC8eS2Z8+e7saNG/3dcGOLADUcj59HqI5wHvXiO9OrVq3q98M2fh5n+aJOvDZsEcjGz8fHcblr3MQo"
				+ "PhP1x/vlXovPR9CKs+fxGELXeL/Ua5Offd9nxu/FPMMjzOOXGLFfbvt/3j948GB3/fr1ZYNv1I5exBa/qBiOJ5+P3xuOd+3a1f9yJYLu+0"
				+ "KvKxCS/0NVjgABAgQIECCQICAUJyAqQSBDIIJg3Ik3wlnsh238fPyZeH0IicPx5D4CZ4T4+Ln4m6zj/XKv3bt3r5/OEIoj7MVjvF/qtQ/5"
				+ "zPjn46x5zHUI97FfbovA/7HvR7iNn10u+LqJW8YqVoMAAQIECBAgUE9AKK7XMyMmQIAAAQIECBAgQIAAgSQBoTgJUhkCBAgQIECAAAECBA"
				+ "gQqCcgFNfrmRETIECAAAECBAgQIECAQJKAUJwEqQwBAgQIECBAgAABAgQI1BMQiuv1zIgJECBAgAABAgQIECBAIElAKE6CVIYAAQIECBAg"
				+ "QIAAAQIE6gkIxfV6ZsQECBAgQIAAAQIECBAgkCQgFCdBKkOAAAECBAgQIECAAAEC9QSE4no9M2ICBAgQIECAAAECBAgQSBIQipMglSFAgA"
				+ "ABAgQIECBAgACBegJCcb2eGTEBAgQIECBAgAABAgQIJAkIxUmQyhAgQIAAAQIECBAgQIBAPQGhuF7PjJgAAQIECBAgQIAAAQIEkgSE4iRI"
				+ "ZQgQIECAAAECBAgQIECgnoBQXK9nRkyAAAECBAgQIECAAAECSQJCcRKkMgQIECBAgAABAgQIECBQT0AortczIyZAgAABAgQIECBAgACBJA"
				+ "GhOAlSGQIECBAgQIAAAQIECBCoJyAU1+uZERMgQIAAAQIECBAgQIBAkoBQnASpDAECBAgQIECAAAECBAjUExCK6/XMiAkQIECAAAECBAgQ"
				+ "IEAgSUAoToJUhgABAgQIECBAgAABAgTqCQjF9XpmxAQIECBAgAABAgQIECCQJCAUJ0EqQ4AAAQIECBAgQIAAAQL1BITiej0zYgIECBAgQI"
				+ "AAAQIECBBIEhCKkyCVIUCAAAECBAgQIECAAIF6AkJxvZ4ZMQECBAgQIECAAAECBAgkCQjFSZDKECBAgAABAgQIECBAgEA9AaG4Xs+MmAAB"
				+ "AgQIECBAgAABAgSSBITiJEhlCBAgQIAAAQIECBAgQKCegFBcr2dGTIAAAQIECBAgQIAAAQJJAkJxEqQyBAgQIECAAAECBAgQIFBPQCiu1z"
				+ "MjJkCAAAECBAgQIECAAIEkAaE4CVIZAgQIECBAgAABAgQIEKgnIBTX65kREyBAgAABAgQIECBAgECSgFCcBKkMAQIECBAgQIAAAQIECNQT"
				+ "EIrr9cyICRAgQIAAAQIECBAgQCBJQChOglSGAAECBAgQIECAAAECBOoJCMX1embEBAgQIECAAAECBAgQIJAkIBQnQSpDgAABAgQIECBAgA"
				+ "ABAvUEhOJ6PTNiAgQIECBAgAABAgQIEEgSEIqTIJUhQIAAAQIECBAgQIAAgXoCQnG9nhkxAQIECBAgQIAAAQIECCQJCMVJkMoQIECAAAEC"
				+ "BAgQIECAQD0Bobhez4yYAAECBAgQIECAAAECBJIEhOIkSGUIECBAgAABAgQIECBAoJ6AUFyvZ0ZMgAABAgQIECBAgAABAkkCQnESpDIECB"
				+ "AgQIAAAQIECBAgUE9AKK7XMyMmQIAAAQIECBAgQIAAgSQBoTgJUhkCBAgQIECAAAECBAgQqCcgFNfrmRETIECAAAECBAgQIECAQJKAUJwE"
				+ "qQwBAgQIECBAgAABAgQI1BMQiuv1zIgJECBAgAABAgQIECBAIElAKE6CVIYAAQIECBAgQIAAAQIE6gkIxfV6ZsQECBAgQIAAAQIECBAgkC"
				+ "QgFCdBKkOAAAECBAgQIECAAAEC9QSE4no9M2ICBAgQIECAAAECBAgQSBIQipMglSFAgAABAgQIECBAgACBegJCcb2eGTEBAgQIECBAgAAB"
				+ "AgQIJAkIxUmQyhAgQIAAAQIECBAgQIBAPQGhuF7PjJgAAQIECBAgQIAAAQIEkgSE4iRIZQgQIECAAAECBAgQIECgnoBQXK9nRkyAAAECBA"
				+ "gQIECAAAECSQJCcRKkMgQIECBAgAABAgQIECBQT0AortczIyZAgAABAgQIECBAgACBJAGhOAlSGQIECBAgQIAAAQIECBCoJyAU1+uZERMg"
				+ "QIAAAQIECBAgQIBAkoBQnASpDAECBAgQIECAAAECBAjUExCK6/XMiAkQIECAAAECBAgQIEAgSUAoToJUhgABAgQIECBAgAABAgTqCQjF9X"
				+ "pmxAQIECBAgAABAgQIECCQJCAUJ0EqQ4AAAQIECBAgQIAAAQL1BITiej0zYgIECBAgQIAAAQIECBBIEhCKkyCVIUCAAAECBAgQIECAAIF6"
				+ "AkJxvZ4ZMQECBAgQIECAAAECBAgkCQjFSZDKECBAgAABAgQIECBAgEA9AaG4Xs+MmAABAgQIECBAgAABAgSSBITiJEhlCBAgQIAAAQIECB"
				+ "AgQKCegFBcr2dGTIAAAQIECBAgQIAAAQJJAkJxEqQyBAgQIECAAAECBAgQIFBPQCiu1zMjJkCAAAECBAgQIECAAIEkAaE4CVIZAgQIECBA"
				+ "gAABAgQIEKgnIBTX65kREyBAgAABAgQIECBAgECSgFCcBKkMAQIECBAgQIAAAQIECNQTEIrr9cyICRAgQIAAAQIECBAgQCBJQChOglSGAA"
				+ "ECBAgQIECAAAECBOoJCMX1embEBAgQIECAAAECBAgQIJAkIBQnQSpDgAABAgQIECBAgAABAvUEhOJ6PTNiAgQIECBAgAABAgQIEEgSEIqT"
				+ "IJUhQIAAAQIECBAgQIAAgXoCQnG9nhkxAQIECBAgQIAAAQIECCQJCMVJkMoQIECAAAECBAgQIECAQD0Bobhez4yYAAECBAgQIECAAAECBJ"
				+ "IEhOIkSGUIECBAgAABAgQIECBAoJ6AUFyvZ0ZMgAABAgQIECBAgAABAkkCQnESpDIECBAgQIAAAQIECBAgUE9AKK7XMyMmQIAAAQIECBAg"
				+ "QIAAgSQBoTgJUhkCBAgQIECAAAECBAgQqCcgFNfrmRETIECAAAECBAgQIECAQJKAUJwEqQwBAgQIECBAgAABAgQI1BMQiuv1zIgJECBAgA"
				+ "ABAgQIECBAIElAKE6CVIYAAQIECBAgQIAAAQIE6gkIxfV6ZsQECBAgQIAAAQIECBAgkCQgFCdBKkOAAAECBAgQIECAAAEC9QSE4no9M2IC"
				+ "BAgQIECAAAECBAgQSBIQipMglSFAgAABAgQIECBAgACBegJCcb2eGTEBAgQIECBAgAABAgQIJAkIxUmQyhAgQIAAAQIECBAgQIBAPQGhuF"
				+ "7PjJgAAQIECBAgQIAAAQIEkgSE4iRIZQgQIECAAAECBAgQIECgnsD/ANKQPxIQz4fiAAAAAElFTkSuQmCC", 
				"/Users/jamyo9/Movies/GestDepo/Imgs/Rondo_5X2.jpg", 0l, null, "https://www.youtube.com/watch?v=YdkeJaPR3v0", 1L, 1L);
		exercises.add(e);
		
		m = new MaterialVO(2L, "Cones", 6);
		materials = new ArrayList<MaterialVO>();
		materials.add(m);
		e = new ExerciseVO(2L, "Empty Cone", "Description para el Empty Cone", 5, "Objetive of the exercise", materials, 0l, "", "", 0l, null, "http://www.youtube.com/watch?v=nOEw9iiopwI", 1L, 1L);
		exercises.add(e);
	}
}
